# Generated by Django 5.2.8 on 2025-11-15 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_meja', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200)),
                ('kode_barang', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('BAIK', 'Baik'), ('RUSAK', 'Rusak'), ('PERBAIKAN', 'Dalam Perbaikan'), ('HILANG', 'Hilang')], default='BAIK', max_length=20)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori')),
                ('meja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.meja')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanKerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('status_laporan', models.CharField(choices=[('Baru', 'Baru'), ('Diproses', 'Sedang Diproses'), ('Selesai', 'Selesai')], default='Baru', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barang')),
            ],
        ),
    ]
