# Generated by Django 5.2.8 on 2025-11-19 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('nama_barang', models.CharField(max_length=150)),
                ('status_barang', models.CharField(choices=[('BAIK', 'Baik'), ('RUSAK', 'Rusak'), ('PERBAIKAN', 'Sedang Perbaikan'), ('HILANG', 'Hilang')], default='BAIK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_meja', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BarangLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi_awal', models.CharField(max_length=150)),
                ('lokasi_akhir', models.CharField(max_length=150)),
                ('waktu_pindah', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barang')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisbarang'),
        ),
        migrations.AddField(
            model_name='jenisbarang',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori'),
        ),
        migrations.CreateModel(
            name='LaporanKerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status_laporan', models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barang')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='meja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.meja'),
        ),
    ]
