# Generated by Django 5.2.8 on 2025-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status_barang',
            field=models.CharField(choices=[('BAIK', 'Baik'), ('RUSAK', 'Rusak'), ('PERBAIKAN', 'Dalam Perbaikan'), ('HILANG', 'Hilang')], default='BAIK', max_length=20),
        ),
        migrations.AlterField(
            model_name='jenisbarang',
            name='nama_jenis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meja',
            name='nama_meja',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='jenisbarang',
            unique_together={('kategori', 'nama_jenis')},
        ),
        migrations.AlterUniqueTogether(
            name='meja',
            unique_together={('nama_meja', 'lokasi')},
        ),
    ]
