# Generated by Django 5.2.8 on 2025-11-20 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_barang_status_barang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baranglog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporankerusakan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jenisbarang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='status_barang',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('dipakai', 'Dipakai'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='tersedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='baranglog',
            name='lokasi_akhir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_akhir', to='core.meja'),
        ),
        migrations.AlterField(
            model_name='baranglog',
            name='lokasi_awal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_awal', to='core.meja'),
        ),
        migrations.AlterField(
            model_name='laporankerusakan',
            name='status_laporan',
            field=models.CharField(choices=[('pending', 'Pending'), ('diperbaiki', 'Diperbaiki'), ('selesai', 'Selesai')], default='pending', max_length=20),
        ),
    ]
