# Generated by Django 5.2.8 on 2025-11-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_baranglog_user_laporankerusakan_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status_barang',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('dipakai', 'Dipakai'), ('rusak', 'Rusak'), ('hilang', 'Hilang'), ('arsip', 'Arsip')], default='tersedia', max_length=20),
        ),
    ]
