# Generated by Django 5.2.8 on 2025-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_barang_status_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status_barang',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('dipakai', 'Dipakai'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='tersedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='laporankerusakan',
            name='foto_url',
            field=models.ImageField(blank=True, null=True, upload_to='laporan_image/'),
        ),
    ]
