# Generated by Django 5.2.8 on 2025-12-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_barang_status_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/barang/'),
        ),
    ]
